/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dashboard/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["LoginResponse"];
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List of payments */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
                     *      */
                    sort?: components["parameters"]["sort"];
                    /** @description status of payment (completed , processing , or failed) */
                    status?: components["schemas"]["PaymentStatus"];
                    /** @description payment id */
                    id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PaymentListResponse"];
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: number;
            message: string;
        };
        User: {
            email: string;
            role: components["schemas"]["UserRole"];
            token: string;
        };
        /** @enum {string} */
        UserRole: "cs" | "operation";
        Payment: {
            /** @example 1 */
            id: string;
            /** @example Merchant A */
            merchant: string;
            status: components["schemas"]["PaymentStatus"];
            /**
             * Format: int64
             * @example 125000
             */
            amount: number;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        PaymentStatus: "completed" | "processing" | "failed";
    };
    responses: {
        /** @description return token and user information */
        LoginResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Payment List */
        PaymentListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    payments?: components["schemas"]["Payment"][];
                };
            };
        };
        /** @description Authentication failed or missing credentials */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body or query parameter is invalid */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
         *      */
        sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
