// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PaymentStatus.
const (
	PaymentStatusCompleted  PaymentStatus = "completed"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusProcessing PaymentStatus = "processing"
)

// Defines values for UserRole.
const (
	Cs        UserRole = "cs"
	Operation UserRole = "operation"
)

// Defines values for GetDashboardV1PaymentsParamsStatus.
const (
	GetDashboardV1PaymentsParamsStatusCompleted  GetDashboardV1PaymentsParamsStatus = "completed"
	GetDashboardV1PaymentsParamsStatusFailed     GetDashboardV1PaymentsParamsStatus = "failed"
	GetDashboardV1PaymentsParamsStatusProcessing GetDashboardV1PaymentsParamsStatus = "processing"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    int64         `json:"amount"`
	CreatedAt time.Time     `json:"created_at"`
	Id        string        `json:"id"`
	Merchant  string        `json:"merchant"`
	Status    PaymentStatus `json:"status"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PaymentSummary defines model for PaymentSummary.
type PaymentSummary struct {
	Completed  int `json:"completed"`
	Failed     int `json:"failed"`
	Processing int `json:"processing"`
	Total      int `json:"total"`
}

// User defines model for User.
type User struct {
	Email string   `json:"email"`
	Role  UserRole `json:"role"`
	Token string   `json:"token"`
}

// UserRole defines model for UserRole.
type UserRole string

// Sort defines model for sort.
type Sort = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments []Payment      `json:"payments"`
	Summary  PaymentSummary `json:"summary"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *GetDashboardV1PaymentsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetDashboardV1PaymentsParamsStatus defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParamsStatus string

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXS2/bRhD+K4tpDwlKm1ScFCmBHpw+AhcJYNh1e3CFes0dSZuSu/Tu0rFq8L8Xs8un",
	"RFmqm0tPtrTz+Gbmm4ceIdNFqRUqZyF9hJIbXqBD4z9ZbRz9FWgzI0sntYIUftBFwY8skqxDwUiKLSTm",
	"wh4zetSKldw5NMqm7OYoM0hyf3J3w16UBhfygd0c3bDvGdl9yW54oStFj0qz0Tu32cs/FEQgye9dhWYN",
	"ESheIKQBXAQ2W2HBCSU+8KLM6WngEiJw69LLOyPVEuq6jsCgLbWy6KN8x8UF3lVo3U/GaENfZVo5VD52",
	"Xpa5zDjFHn+yWg08eW2p7nkuWwv0ja2Kgps1pHAW3pgJj+xWizXThvlIWJdriOCe5xUGzwIhfZ0kERRo",
	"LV8ipCDHdkIMfeBfG1xACl/FfS3j8GrjEJJXGFfx4mlMTFrWuIU6gjNF5eT5JZp7NM/L06SFPllXCh9K",
	"zDyjvAxDL7SVnDebyQmGx1pfIkW7ENURfNBLqS4aFh2QicOQXFmcBGLQVUYxp/9CxbgSrLJUIbXQpvB+",
	"CNI5Xxeo3Adp3bOAlUaXaJzEZhB4a/5/6bCw+7A37qHuGo4bw9f0uavxQRYuG+nQp3eVNCggve4R9Qbn",
	"nS99+wkzN5W7xiqjvBCYK8Urt9JG/o3iOTyuvD4qR0Ioxhz+KK2Vakn91PasL9pUh8+GJL4aW01ZscvS",
	"lyD2ae9LasUWXOYoyFXrNTMoSIDnFnp/Pv4uZ2O+hKge23pQUy7Rt0oX5OPWJB4X2Jvo5beL23F8231Y",
	"IaMtMHv1JqFJEZokYPr2NTmQShZVAWkSTcAdrI70sVcW3OGRkwVuL5QIpBh5htmUUIEmW/ENkPCx+Zad",
	"TulYx111aOtdBuHNtEoBA+edzajN2SjkJ5J+2WFBVRWhYBQENUFE5cjQkwciCISC+UREG00+waPW5qiW",
	"J/vK1rgcKr3dpzPAPNT7bp+e047nI5WT5GmdjZIEA9G/SGBfDb8jttKGBZf5RItFYHSOh+ydC5LzwdGU",
	"2duswWFjvtXahfeiwdARx0IEBD8sr22eEPUxq4x060vCGIK8RW7Q0PDqP/3cNugvv//aXoNkKbz2PbVy",
	"rgyjkNamj0+60IHr9/oDV8vTsmSn52c0qtHYMChnx8lxQlHoEhUvJaRwcpwcn1C9uFt5VLHgdnWruRHx",
	"/SymMR7ndB34IulwEnaxnglaSdq6H1ul32YUkL8nIKQYrXunxfo/LO/dbCi5tZ+1EYcXuNOYXra9ijMV",
	"bp7Wr5JkF/c6uXh8S9URvD5Ea/Nq93qz/Xrb+7+O4M0hHqdu4Hp43oSrkH2WbsV8+tg3rEsfSY6pMjyx",
	"ljjBk/c4pMl5f/8Mf6VdT8PuRWL/Q6mONn/GhT3A9II1QNiLbh6xiPXziEV0GoSR9HLXj7F2qfSUfP6W",
	"2MbaIpRih38pRr43Dc6fw8upg/p/yM5mjnqmDCfo9byej8grrRuwwTaXpjcXeFaZvJmkaRznOuP5SluX",
	"vk3eJlDP638GADd1Z8VMEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
